### PR TITLE
Fix: add nginx rules for subdir installs

### LINKED ISSUE #782: Unable to access admin for new WordCamp site in Docker local
**Describe the bug**

After setting up a local environment running using the [Docker](https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md) instructions, and creating a new WordCamp and its site, I was unable to browse to the site.

Blocking: #777 

**To reproduce**

1. Setup your local environment using [Docker](https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md).
2. Create a new WordCamp at https://central.wordcamp.test/wp-admin/post-new.php?post_type=wordcamp.  Mine was `Ryan 2022`.
3. Advance the WordCamp to a status of "Needs Site" and enter any required information.
4. Fill in the URL field (mine was `https://ryan.wordcamp.test/2022/`), check the box to `Created site in network`, and change the status to `Needs Crowdsignal Account`.
5. Add to my `/etc/hosts` file an entry for my WordCamp.  Mine is
> 127.0.0.1 	wordcamp.test central.wordcamp.test city.wordcamp.test ryan.wordcamp.test
6. Browse to https://wordcamp.test/wp-admin/network/sites.php and see the site.
7. Click on Dashboard under my new site: https://ryan.wordcamp.test/2022/wp-admin/.  See the following error:
> This page isn’t working
ryan.wordcamp.test redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS
8. Clear all cookies following the instructions above.
9. Browse to https://ryan.wordcamp.test/2022/wp-admin/.  Continue to see the error
10. Browse to https://ryan.wordcamp.test/2022/. Can see the new site's public pages without issue.
 
Attached is a zipped .HAR file.
[ryan.wordcamp.test.har.zip](https://github.com/WordPress/wordcamp.org/files/8894554/ryan.wordcamp.test.har.zip)

**Expected behavior**

I would be able to see the /wp-admin interface for the Ryan 2022 WordCamp.

**Screenshots**

image

image

**System (please complete the following information):**

 - Device: MBP
 - OS: macOS Monterey 12.4
 - Browser Chrome
 - Version 102.0.5005.115 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by 2ndkauboy**
The nginx.conf was missing some configuration for backends of individual WordCamps to work then using the year as a subdirectory, which is the default now.

Fixes #782

Props @nullbytes

### How to test the changes in this Pull Request:

1. Install the environment
2. Change the domain from 2014.seattle.wordcamp.org to seattle.wordcamp.org/2014
3. Try to access https://seattle.wordcamp.org/2014/wp-admin

### CODE REVIEW

**Review by ryelle — COMMENTED** [review]
This does fix the year subdomains, so `city.wordcamp.test/year/` works again. I didn't test that the edited database file works (I don't want to blow away my test site right now), but I do see more transients than before, and the file is almost 2MB larger.

I'd approve this if you dropped the database dump, or managed to only change the URLs.

FYI @adamwoodnz — this might be a good one to test at WCEU, or at least have on your radar in case contributors run into issues.

**Comment by 2ndkauboy** [comment]
Then I'll be happy to test it at the WCEU Contributor Day again 😁

**Comment by iandunn** [comment]
Er, I forgot this PR was open, so I added some overlapping stuff in #933. Some of this may still be necessary depending on how the tests in #782 go, though

**Comment by timiwahalahti** [comment]
Since #782 and #778 tested to be working, closing this.

**Pull request closed without merging**
