### PR TITLE
Add registration question for first-time attendees

### PR DESCRIPTION
**Pull request by iandunn**
See #875

WIP

Testing:
* Answer `yes`, `no`, `unsure`, and skip the question
* Check meta values in the CPT item, and also Summarize tool, attendee export

### CODE REVIEW

**Comment by iandunn** [comment]
Hey @catederosia 👋🏻 , I have a few questions:

1. Should this question be required, or optional? 

    I'm leaning towards optional because that'd reduce the burden on users when filling out the form. It'd also mean that we'd get less data, though, and that the data we would get may be biased in one direction or the other. First-time attendees may be more or less motivated to answer the question, so it wouldn't be a random sample.

1. What event type(s) should this ask about?

    Currently I have it saying:

    > Will this be your first time attending a WordPress event? 

    We could also have it insert the type of event being registered for, though, like:

    > Will this be your first time attending a WordCamp? 
    > Will this be your first time attending a Pilot Event? 
    > etc

    Tracking it for different types would add some complexity, but I'm sure not how important having the data separated is.

**Comment by catederosia** [comment]
Apologies for the delay @iandunn. 

1. It's a small enough question, let's make it required.
2. If it's not too much extra work, it would be ideal to have it ask it insert the type of event being registered for. It would give us more specific data.

I am sway-able on both. I value your experience here.

**Comment by iandunn** [comment]
Those sound good 👍🏻  I'll work on getting the specific data, and follow up if it turns out to be more complicated than expected.

**Comment by iandunn** [comment]
I looked at asking the question based on the event type, but that's going to depend on how some other issues are done, so it's currently blocked. For now I just asked about WP events in general. I added a checklist item to #875 to track it.

**Comment by StevenDufresne** [comment]
Circling back here, I don't know that the attendees will see a distinct line between the 2 types. Attendees would need to be very aware of the difference and I don't think we, as organizers are super clear on where the line is drawn. I say we don't go this route. We could revisit if it seems like it would provide significant insight. Is that okay with everyone?

**Pull request merged**
