### PR TITLE
Travis: Run unit test suite

### PR DESCRIPTION
**Pull request by iandunn**
I started working on this, but didn't get very far. @vedanshujain, how did you test the original config before committing it? I couldn't find any good info on that.

Also, do you have any feedback on this?

In addition to running the tests, I pulled in some stuff from Core's config.

### CODE REVIEW

**Comment by iandunn** [comment]
We should switch to phpunit 7.x, since that's the latest version that Core's framework supports.

**Comment by iandunn** [comment]
> how did you test the original config before committing it? I couldn't find any good info on that.

looks like you can [run it locally in a Docker instance](https://stackoverflow.com/a/43625282/450127)

it sounds like it should also work by sending a PR, but it doesn't look like this PR was tested.

**Comment by vedanshujain** [comment]
I think I tested it by committing changes to PR, but clearly tests are not running for this one. Let me know if you want to pair up for this. 
BTW kudos for adding unit tests infra , looks like a well needed addition.

**Comment by iandunn** [comment]
GH closed then when I renamed `master` to `production`, but it's still active. There's no way to reopen it, though, so we'll have to open a new PR instead.

I'll re-submit this.

**Pull request closed without merging**
