### PR TITLE
Update past events template to align with design

### LINKED ISSUE #1178: Add Past Events template
See https://www.figma.com/file/jdMk5ssz2Av7KFfEaeK7de/Events?type=design&node-id=1617-13838&mode=dev

### PR DESCRIPTION
**Pull request by outdoor2kode**
See #1178
Design: https://www.figma.com/file/jdMk5ssz2Av7KFfEaeK7de/Events?type=design&node-id=1617-13838&mode=dev

### Screenshots

Screenshot 2024-04-23 at 13 39 26

### How to test the changes in this Pull Request:

1. setup the event env
2. go to /past-events
3. the view of the page should match the design

### CODE REVIEW

**Review by pkevan — APPROVED** [review]
👍

**Comment by StevenDufresne** [comment]
Where is this page linked in the theme?

**Comment by StevenDufresne** [comment]
Also, when I apply [this filter](https://events.wordpress.org/past-events/filtered/month/03/), I don't get expected results. The result set doesn't change.

Screenshot 2024-04-30 at 9 45 32 AM

**Comment by outdoor2kode** [comment]
@StevenDufresne 

Both of these have been noticed, but:
1. I discovered when working on this ticket that the past event page has always existed; it just hasn't been placed anywhere on the site. I'm not sure why, perhaps it's due to the page wasn't completely aligned with the design, so I made the page follow the design first (this PR).
2. As for where to place its link, I'm tempted to wait for the community team to present a complete plan for the event site and address it all at once. I would like the design team to focus on this project more consistently, rather than pinging them now about this one issue and that's it. I hope they can handle more about the event at once, giving us a more cohesive and comprehensive view of it.
3. I feel that since it hasn't been used for a long time, there's no rush to activate it now, especially since the filter is still broken.

**Pull request merged**
