### PR TITLE
Feature/attendance ui questions

### PR DESCRIPTION
**Pull request by vedanshujain**

### CODE REVIEW

**Comment by vedanshujain** [comment]
lgtm. @dd32 can you please also apply the code standard changes suggested by phpcs (https://travis-ci.com/WordPress/wordcamp.org/builds/106896831, just the ones reported for your code change, no need to fix for whole file ).

**Comment by iandunn** [comment]
Bumped the limit in 019063567766ef3478c556fd4fc2dd8b09cca668 :)

**Comment by dd32** [comment]
https://meta.trac.wordpress.org/changeset/8605 

Marking this PR as closed, @mention me if any fixes or changes are needed.

**Comment by iandunn** [comment]
Thanks!

**Pull request closed without merging**
