### PR TITLE
Automate request approval 

### PR DESCRIPTION
**Pull request by iandunn**
if the request is within the approved budget, there's no need for manual approval

Supercedes #19

### CODE REVIEW

**Comment by timiwahalahti** [comment]
Not sure if we want this anymore, actually. During the budget review deputy discuss essential topics with the organisers, and even if the budget is within approved limits, there might be single lines the reviewer asks to change (like an imbalance between some costs).

What do you think @kcristiano, @harmonyromo, @dorsvenabili, @angelasjin?

**Comment by kcristiano** [comment]
@timiwahalahti I agree I don't think automatic approval is warranted any longer.

**Comment by harmonyromo** [comment]
I would agree

**Comment by dorsvenabili** [comment]
I agree with not automating the approval.

**Comment by timiwahalahti** [comment]
Going to close this PR per voiced opinions of not doing automated budget approvals.

**Pull request closed without merging**
