### PR TITLE
Blocks: Add query loop variations for WordCamp post types

### LINKED ISSUE #797: Blocks: Add Query Loop variations for WordCamp post types
[Block variations can be used to extend the Query Loop block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/) to natively support custom content types, like Sessions, Sponsors, etc. 

Using the Query Loop block plus [the helper blocks that were added here](https://github.com/WordPress/wordcamp.org/pulls?q=is%3Apr+project%3Awordpress%2Fwordcamp.org%2F2+is%3Aclosed+label%3A%22%5BComponent%5D+Blocks%22) can create more customizable layouts for WordCamps.

Related: #756 & #760 which add Query Loop patterns.

### PR DESCRIPTION
**Pull request by ryelle**
This adds special query loop variations for the rest of the WordCamp post types (Organizers, Speakers, Sponsors), so that it's easier to use the query loop with our content types.

The Query approach is more flexible, allowing organizers to move around blocks and adjust the formatting on a per-block level. Eventually, these could replace the old list blocks in the new site content. Until then, they're kind of a hidden feature, discovered by searching the blocks list for "speakers", etc. (once this is merged, I'll add another issue to update the new content)

When added, these new blocks set up a default query (10 items per page, sorted A-Z), which can be updated to filter a specific taxonomy (or any other changes). It also drops in set of default blocks, different for each post type.

**Organizers**
- A row with organizer avatar & name
- Post excerpt
- A row with "Teams:" and the teams tagged to this organizer

**Speakers**
- A row with speaker avatar & name
- Post excerpt
- Speaker sessions list, showing session details and linking to each session

**Sponsors**
- Featured image, linked to sponsor post
- Post title, linked to sponsor post
- Post excerpt

This also updates the session list variation with a new icon, and updates the attributes on the group block.

Fixes #797, See #754

### Screenshots

| | Screenshot |
|---|---|
| organizers |  |
| sessions |  |
| sponsors |  |
| speakers |  |

These blocks all have custom icons to differentiate them from the old list blocks:

### How to test the changes in this Pull Request:

1. Have content set up on your site
2. Add any of these list blocks
3. It should display the content you chose
4. Changing the filters should apply to the content

### CODE REVIEW

**Review by pkevan — APPROVED** [review]
Code looks good, although was unable to test this.

My only thoughts on testing were testing limits and results, i.e. can all speakers be listed, what happens when it's 0. Since I couldn't test, I'm presuming this is possible in the UI.

**Comment by ryelle** [comment]
It inherits the controls from the Query Loop, so organizers can control the number displayed in the toolbar settings:

Screenshot 2023-05-22 at 10 40 14 AM

To show all [type], you can set the value to 100 — the upper limit in the UI, or higher by editing the code itself (I don't have an install with that many anything so I don't know if it will limit eventually). If you set it to 0 (in code, not possible in UI), it's invalid and defaults back to 3.

**Comment by pkevan** [comment]
> If you set it to 0 (in code, not possible in UI), it's invalid and defaults back to 3.

Does the text need to change if it's not possible to show all via the UI?

**Comment by ryelle** [comment]
> Does the text need to change if it's not possible to show all via the UI?

I don't think so, it's the same behavior as the regular query loop block and if someone has that many speakers it will paginate:

Screenshot 2023-05-22 at 11 21 58 AM

**Comment by pkevan** [comment]
Oh, mis-read the max page text thinking it related to the total number - ignore me!

**Pull request merged**
