### PR TITLE
Try using MariaDB LTS to reduce need for Apple Silicon workarounds.

### PR DESCRIPTION
**Pull request by dd32**
Tested on Apple M1 Max

Fixes #, See #

Props <username>, <username>

### How to test the changes in this Pull Request:

1.
2.
3.

### CODE REVIEW

**Comment by pkevan** [comment]
I ran into similar issues and had the same thoughts about switching to mariadb to not only work better for apple silicon but to match closer to production.

**Comment by dd32** [comment]
As far as I've been able to tell, this PR change "just works".

The `mysql` CLI tools should be the same (or compatible).

The `webserver` container also seems to just build under arm now, maybe there was an issue with a dependency in the past, but it seems to be fine now..

**Comment by pkevan** [comment]
Yeah, I figured it probably would, and therefore no reason not to do it.

I'll test today on my current machine, and previous (intel) machine and see about merging (as it's annoying me too!)

**Comment by pkevan** [comment]
> previous (intel) machine

what I hadn't banked on was the many GBs of downloads for docker, brew etc!

**Comment by pkevan** [comment]
Eurgh, giving up running this on my old machine for this week (too many problems), will try again next week!

**Comment by pkevan** [comment]
@dd32 did you make any other changes to the files to make this work? i'm struggling to get it working.

**Comment by hideokamoto** [comment]
I encountered the following error during the docker compose build --pull process:

```
% docker compose build --pull
[+] Building 17.0s (12/36)                                                                                  
 => [wordcamptest_wordcamp.test internal] load build definition from Dockerfile.php-fpm                0.0s
 => => transferring dockerfile: 2.40kB                                                                 0.0s
 => [wordcamptest_wordcamp.db internal] load build definition from Dockerfile.mysql                    0.0s
 => => transferring dockerfile: 307B                                                                   0.0s
 => [wordcamptest_wordcamp.test internal] load .dockerignore                                           0.0s
 => => transferring context: 2B                                                                        0.0s
 => [wordcamptest_wordcamp.db internal] load .dockerignore                                             0.0s
 => => transferring context: 2B                                                                        0.0s
 => [wordcamptest_wordcamp.test internal] load metadata for docker.io/library/php:7.4-fpm              1.5s
 => [wordcamptest_wordcamp.db internal] load metadata for docker.io/library/mysql:5.7-debian           1.4s
 => CACHED [wordcamptest_wordcamp.db 1/3] FROM docker.io/library/mysql:5.7-debian@sha256:0821f3a5b3ec  0.0s
 => [wordcamptest_wordcamp.db internal] load build context                                             0.1s
 => => transferring context: 68B                                                                       0.0s
 => CACHED [wordcamptest_wordcamp.test  1/25] FROM docker.io/library/php:7.4-fpm@sha256:3ac7c8c74b2b0  0.0s
 => [wordcamptest_wordcamp.test internal] load build context                                           0.1s
 => => transferring context: 234B                                                                      0.0s
 => ERROR [wordcamptest_wordcamp.db 2/3] RUN apt-get update     && apt-get install -y         nano    15.2s
 => CANCELED [wordcamptest_wordcamp.test  2/25] RUN apt-get update     && apt-get install -y          15.3s
------                                                                                                      
 > [wordcamptest_wordcamp.db 2/3] RUN apt-get update     && apt-get install -y         nano         vim:    
#7 4.778 Get:1 http://repo.mysql.com/apt/debian buster InRelease [22.1 kB]                                  
#7 5.003 Err:1 http://repo.mysql.com/apt/debian buster InRelease                                            
#7 5.003   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C                                                                                            
#7 5.089 Get:2 http://deb.debian.org/debian buster InRelease [122 kB]                                       
#7 5.498 Get:3 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]                     
#7 6.387 Get:4 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]                              
#7 8.819 Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]                            
#7 12.15 Get:6 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [585 kB]            
#7 12.41 Get:7 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]                     
#7 14.21 Reading package lists...
#7 15.17 W: GPG error: http://repo.mysql.com/apt/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
#7 15.17 E: The repository 'http://repo.mysql.com/apt/debian buster InRelease' is not signed.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apt-get update     && apt-get install -y         nano         vim]: exit code: 100
```



After switching to MariaDB, it worked.
I really appreciate this PR.

**Comment by dd32** [comment]
> @dd32 did you make any other changes to the files to make this work? i'm struggling to get it working.

Not that I'm aware of.. After a few failed install attempts, I made this change and everything just worked.

**Comment by pkevan** [comment]
I've never been able to successfully run Mariadb on my m1 max machine with these changes, however I was able to update to mysql 8:

`FROM mysql:8.0-debian`

**Comment by candy02058912** [comment]
Changing `mysql:5.7-debian` to `mysql:8.0-debian` also worked for me for this particular step.

**Comment by dd32** [comment]
Set it up from scratch today using this PR, without issue.

Closing in favour of the merged #1261 though, which also worked first go.

**Pull request closed without merging**
