### PR TITLE
Blocks: Refine Speakers/Sessions/Sponsors blocks and related shared components

### PR DESCRIPTION
**Pull request by vedanshujain**
@iandunn I have added extra commits from feature/additional-blocks here, but I am not sure if I got everything. Can you verify and then close https://github.com/WordPress/wordcamp.org/pull/33 if needed

### Unresolved conversations from #33:

@vedanshujain :
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r262289298
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r262291133 
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r262291863
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r263624465
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r263624723 
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r263624953
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r263628471  
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r263979094 
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r267487319  
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r267525531  
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r267099975 
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r267525531 
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r266021525 
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r267139760 
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r266133019 
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r266133488 
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r266168141

@coreymckrill :
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r267825310 
- [x] https://github.com/WordPress/wordcamp.org/pull/33#discussion_r268691970 
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r266171207  
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r266170608 
- [x] `VersatileSelect` still exists in `master` even though it was deleted in b15755f12403a626d76126479ac31d705349204f from #33 . It should probably just be removed again, but why is it still there? Did we miss other changes when merging #33 to SVN?
- [x] `.wordcamp-speaker-session-list` says "see note above", but there is nothing above

@iandunn :
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r267140082 - adding `debug` script. fixed in 508984cce4e5a65bc65f907ad369ee7e64928f9c
- [x] https://github.com/WordPress/wordcamp.org/pull/33/files#r267486918 - passing `props` to `super()`- done in 494f7f32c4b2ec095b26cd184f5479c1a3ad1249

### CODE REVIEW

**Comment by iandunn** [comment]
@coreymckrill , everything you committed to #33 should either be in `master` now, or in this branch. Can you verify that?

**Comment by iandunn** [comment]
@vedanshujain , @coreymckrill : I added a checklist of all the unresolved conversations in the PR description. Please mark the corresponding conversation as resolved when you push a commit to this PR to fix it, and then check the box.

Since there's so much here, I'm gonna rename this to just refining the existing blocks, and start a separate PR for adding organizers.

**Comment by iandunn** [comment]
I went ahead and committed the `debug` script directly to `master` in 508984cce4e5a65bc65f907ad369ee7e64928f9c, since it wasn't something that needed review, and that'll be simpler than adding it here, then having to deal with the pain we did in #33. I'll probably do the same for the `super( props )` one once we come to a consensus on how to approach it.

For things that need code review, pushing them here is probably still the best way, though.

**Comment by coreymckrill** [comment]
> everything you committed to #33 should either be in master now, or in this branch. Can you verify that?

I didn't get to this today, but will look tomorrow.

**Comment by coreymckrill** [comment]
> everything you committed to #33 should either be in master now, or in this branch. Can you verify that?

Confirmed--it's all in this new branch.

**Comment by coreymckrill** [comment]
Re: this checklist item:

> VersatileSelect still exists in master even though it was deleted in b15755f from #33 . It should probably just be removed again, but why is it still there? Did we miss other changes when merging #33 to SVN?

That commit, and the others that I made around the same time, were added to 33 after it had already been merged. So those commits were brought over to this PR, but they haven't been merged to `master` yet. I think I am going to just cherry-pick each of the commits we have here so far over to `master`.

**Comment by coreymckrill** [comment]
Alright, I cherry picked all 7 of the commits so far in this branch (up through 15e377aa893c986810bd40a1b784cb975bb476c9) over to SVN/master. Some of them were things that needed to be resolved before the design review in #62, so I just went ahead and did all of them.

**Comment by iandunn** [comment]
@vedanshujain : I added a new checkbox for https://github.com/WordPress/wordcamp.org/pull/33#discussion_r266168141

**Comment by coreymckrill** [comment]
> .wordcamp-speaker-session-list says "see note above", but there is nothing above

Fixed with https://meta.trac.wordpress.org/changeset/8597

**Comment by iandunn** [comment]
👍 

TIL that `/*` comments are included in the build, but `//` aren't.

It seems like it'd be preferable to strip both types of comments, because there's no point in `/*` being included, and using `/*` in `src` will keep it nicer and more consistent w/ coding standards.

More of a long-term priority though, as part of reducing build size. In the mean time I think it'd fine to continue using `/*` comments.

**Comment by iandunn** [comment]
I removed the last 2 items on my list so that we can close this out.

One of them was smaller stuff that was annoying me but isn't worth spending time on; the other one I opened #74

**Comment by iandunn** [comment]
re: comments: actually, I think we'll probably want to preserve comments and in the build, so that organizers who are working on building their custom CSS can read them, which will be informative in many cases.

**Comment by coreymckrill** [comment]
I think it depends on the context of the comment. If the comment is about Sass, it probably won't make any sense in the context of compiled, minified CSS.

**Comment by iandunn** [comment]
That's true, but is there an easy way to strip those without stripping the useful ones? How big of an impact would those Sass-specific comments make on the file size if they were included?

**Pull request closed without merging**
